In [1]:
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct", torch_dtype="auto", device_map="auto"
)

# We recommend enabling flash_attention_2 for better acceleration and memory saving, especially in multi-image and video scenarios.
# model = Qwen2VLForConditionalGeneration.from_pretrained(
#     "Qwen/Qwen2-VL-7B-Instruct",
#     torch_dtype=torch.bfloat16,
#     attn_implementation="flash_attention_2",
#     device_map="auto",
# )

# default processer
processor = AutoProcessor.from_pretrained("/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

# # Preparation for inference
# text = processor.apply_chat_template(
#     messages, tokenize=False, add_generation_prompt=True
# )
# image_inputs, video_inputs = process_vision_info(messages)
# inputs = processor(
#     text=[text],
#     images=image_inputs,
#     videos=video_inputs,
#     padding=True,
#     return_tensors="pt",
# )
# inputs = inputs.to("cuda")

# # Inference: Generation of the output
# generated_ids = model.generate(**inputs, max_new_tokens=128)
# generated_ids_trimmed = [
#     out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
# ]
# output_text = processor.batch_decode(
#     generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
# )
# print(output_text)

/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 5/5 [00:50<00:00, 10.00s/it]


In [12]:
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct", torch_dtype="auto", device_map="auto"
)
print(model)

`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46


Loading checkpoint shards: 100%|██████████| 5/5 [00:39<00:00,  7.88s/it]

Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Seq

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-7B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "write a quick sort algorithm."
messages = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]



/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 4/4 [02:45<00:00, 41.34s/it]


In [2]:
response

'Certainly! Below is a Python implementation of the Quick Sort algorithm:\n\n```python\ndef quick_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    else:\n        pivot = arr[len(arr) // 2]\n        left = [x for x in arr if x < pivot]\n        middle = [x for x in arr if x == pivot]\n        right = [x for x in arr if x > pivot]\n        return quick_sort(left) + middle + quick_sort(right)\n\n# Example usage:\narr = [3, 6, 8, 10, 1, 2, 1]\nsorted_arr = quick_sort(arr)\nprint(sorted_arr)\n```\n\n### Explanation:\n- **Base Case**: If the array has one or zero elements, it is already sorted.\n- **Pivot Selection**: The pivot is chosen as the middle element of the array (for simplicity). Other strategies like choosing the first element or a random element can also be used.\n- **Partitioning**: The array is partitioned into three sub-arrays: `left` (elements less than the pivot), `middle` (elements equal to the pivot), and `right` (elements greater than the pivot).\n- **Recursive 

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-7B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
print(model)

/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 4/4 [00:40<00:00, 10.18s/it]


Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(152064, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=3584, out_features=3584, bias=True)
          (k_proj): Linear(in_features=3584, out_features=512, bias=True)
          (v_proj): Linear(in_features=3584, out_features=512, bias=True)
          (o_proj): Linear(in_features=3584, out_features=3584, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (up_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (down_proj): Linear(in_features=18944, out_features=3584, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm):

In [9]:
qwen2coder_sd = model.model.state_dict()

In [11]:
qwen2coder_sd.keys()

odict_keys(['embed_tokens.weight', 'layers.0.self_attn.q_proj.weight', 'layers.0.self_attn.q_proj.bias', 'layers.0.self_attn.k_proj.weight', 'layers.0.self_attn.k_proj.bias', 'layers.0.self_attn.v_proj.weight', 'layers.0.self_attn.v_proj.bias', 'layers.0.self_attn.o_proj.weight', 'layers.0.mlp.gate_proj.weight', 'layers.0.mlp.up_proj.weight', 'layers.0.mlp.down_proj.weight', 'layers.0.input_layernorm.weight', 'layers.0.post_attention_layernorm.weight', 'layers.1.self_attn.q_proj.weight', 'layers.1.self_attn.q_proj.bias', 'layers.1.self_attn.k_proj.weight', 'layers.1.self_attn.k_proj.bias', 'layers.1.self_attn.v_proj.weight', 'layers.1.self_attn.v_proj.bias', 'layers.1.self_attn.o_proj.weight', 'layers.1.mlp.gate_proj.weight', 'layers.1.mlp.up_proj.weight', 'layers.1.mlp.down_proj.weight', 'layers.1.input_layernorm.weight', 'layers.1.post_attention_layernorm.weight', 'layers.2.self_attn.q_proj.weight', 'layers.2.self_attn.q_proj.bias', 'layers.2.self_attn.k_proj.weight', 'layers.2.self_

In [1]:
import torch
from transformers import (
    Qwen2VLForConditionalGeneration,  # Qwen2-VL
    Qwen2ForCausalLM,                 # Qwen2 / Qwen2.5 coder
)

# 1) 加载 Qwen2-VL 模型
qwen2vl_model_path = "/mnt/lingjiejiang/multimodal_code/exp/saves/qwen2_vl_coder_llm_and_merger-7b_qwen_branch_test/lora/sft"
qwen2vl = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_model_path,
    torch_dtype="auto",  
    device_map="auto"
)

# 2) 加载 Qwen2.5 coder 模型 (或者 Qwen2-7B-Instruct 等)
qwen2coder_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-Coder-7B-Instruct"
qwen2coder = Qwen2ForCausalLM.from_pretrained(
    qwen2coder_model_path,
    torch_dtype="auto",
    device_map="auto"
)


/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 4/4 [00:37<00:00,  9.39s/it]


In [2]:
qwen2coder.model.state_dict()

OrderedDict([('embed_tokens.weight',
              tensor([[-2.3438e-02,  1.3916e-02,  1.0010e-02,  ..., -1.0605e-03,
                       -1.3611e-02, -3.1982e-02],
                      [-6.7139e-03,  1.3123e-02,  8.1787e-03,  ..., -4.2114e-03,
                       -7.3624e-04,  4.4556e-03],
                      [-1.2390e-02,  3.8300e-03, -5.1270e-03,  ..., -1.3924e-04,
                       -2.4658e-02,  1.5076e-02],
                      ...,
                      [-1.1755e-37,  1.1755e-37,  1.1755e-37,  ..., -1.1755e-37,
                        1.1755e-37,  1.1755e-37],
                      [ 1.1755e-37, -1.1755e-37,  1.1755e-37,  ..., -1.1755e-37,
                        1.1755e-37, -1.1755e-37],
                      [ 1.1755e-37, -1.1755e-37, -1.1755e-37,  ...,  1.1755e-37,
                        1.1755e-37, -1.1755e-37]], device='cuda:0', dtype=torch.bfloat16)),
             ('layers.0.self_attn.q_proj.weight',
              tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0

In [11]:
print(qwen2vl)

Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Seq

In [9]:
print(qwen2coder)

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(152064, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=3584, out_features=3584, bias=True)
          (k_proj): Linear(in_features=3584, out_features=512, bias=True)
          (v_proj): Linear(in_features=3584, out_features=512, bias=True)
          (o_proj): Linear(in_features=3584, out_features=3584, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (up_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (down_proj): Linear(in_features=18944, out_features=3584, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm):

In [10]:
qwen2coder.lm_head

Linear(in_features=3584, out_features=152064, bias=False)

In [8]:
# 取出 Qwen2VL 里 “LLM 部分”的 state_dict
qwen2vl_backbone_sd = qwen2vl.model.state_dict()

# 取出 Qwen2Coder (Qwen2.5) 里 “LLM 部分”的 state_dict
qwen2coder_sd = qwen2coder.model.state_dict()

# 遍历 coder 的每个参数，如果在 vl 里有同名参数且形状一致，就直接覆盖
for name, param in qwen2coder_sd.items():
    if name in qwen2vl_backbone_sd and qwen2vl_backbone_sd[name].shape == param.shape:
        # 用 coder 的参数覆盖 VL 的对应参数
        with torch.no_grad():
            qwen2vl_backbone_sd[name].copy_(param)

# 将更新后的 state_dict load 回去
qwen2vl.model.load_state_dict(qwen2vl_backbone_sd)


<All keys matched successfully>

In [46]:
import torch
from transformers import (
    Qwen2VLForConditionalGeneration,  # Qwen2-VL
    Qwen2ForCausalLM,                 # Qwen2 / Qwen2.5 coder
)

# 1) 加载 Qwen2-VL 模型
qwen2vl_model_path = "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct"
qwen2vl = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_model_path,
    torch_dtype="auto",  
    device_map="auto"
)

# 2) 加载 Qwen2.5 coder 模型 (或者 Qwen2-7B-Instruct 等)
qwen2coder_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-Coder-7B-Instruct"
qwen2coder = Qwen2ForCausalLM.from_pretrained(
    qwen2coder_model_path,
    torch_dtype="auto",
    device_map="auto"
)

# 取出 Qwen2VL 里 “LLM 部分”的 state_dict
qwen2vl_backbone_sd = qwen2vl.model.state_dict()

# 取出 Qwen2Coder (Qwen2.5) 里 “LLM 部分”的 state_dict
qwen2coder_sd = qwen2coder.model.state_dict()

# 遍历 coder 的每个参数，如果在 vl 里有同名参数且形状一致，就直接覆盖
for name, param in qwen2coder_sd.items():
    if name in qwen2vl_backbone_sd and qwen2vl_backbone_sd[name].shape == param.shape:
        # 用 coder 的参数覆盖 VL 的对应参数
        with torch.no_grad():
            qwen2vl_backbone_sd[name].copy_(param)

# 将更新后的 state_dict load 回去
qwen2vl.model.load_state_dict(qwen2vl_backbone_sd)


Loading checkpoint shards: 100%|██████████| 4/4 [00:38<00:00,  9.72s/it]


<All keys matched successfully>

In [6]:
print(qwen2vl)

Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Seq

In [48]:
print(qwen2coder)

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(152064, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=3584, out_features=3584, bias=True)
          (k_proj): Linear(in_features=3584, out_features=512, bias=True)
          (v_proj): Linear(in_features=3584, out_features=512, bias=True)
          (o_proj): Linear(in_features=3584, out_features=3584, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (up_proj): Linear(in_features=3584, out_features=18944, bias=False)
          (down_proj): Linear(in_features=18944, out_features=3584, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm):

In [47]:
different_params = []
for name, param in qwen2coder_sd.items():
    if name in qwen2vl_backbone_sd and qwen2vl_backbone_sd[name].shape == param.shape:
        continue
    else:
        different_params.append(name)
print(different_params)

In [14]:
qwen2vl_lm_head_sd = qwen2vl.lm_head.state_dict()
qwen2coder_lm_head_sd = qwen2coder.lm_head.state_dict()
for name, param in qwen2coder_lm_head_sd.items():
    if name in qwen2vl_lm_head_sd and qwen2vl_lm_head_sd[name].shape == param.shape:
        with torch.no_grad():
            qwen2vl_lm_head_sd[name].copy_(param)
qwen2vl.lm_head.load_state_dict(qwen2vl_lm_head_sd)

<All keys matched successfully>

In [1]:
import torch
from transformers import (
    Qwen2VLForConditionalGeneration,  # Qwen2-VL
    Qwen2ForCausalLM,                 # Qwen2 / Qwen2.5 coder
)

# 1) 加载 Qwen2-VL 模型
qwen2vl_model_path = "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct"
qwen2vl = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_model_path,
    torch_dtype="auto",  
    device_map="auto"
)

# 2) 加载 Qwen2.5 coder 模型 (或者 Qwen2-7B-Instruct 等)
qwen2coder_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-Coder-7B-Instruct"
qwen2coder = Qwen2ForCausalLM.from_pretrained(
    qwen2coder_model_path,
    torch_dtype="auto",
    device_map="auto"
)

# 取出 Qwen2VL 里 “LLM 部分”的 state_dict
qwen2vl_backbone_sd = qwen2vl.model.state_dict()

# 取出 Qwen2Coder (Qwen2.5) 里 “LLM 部分”的 state_dict
qwen2coder_sd = qwen2coder.model.state_dict()

# 遍历 coder 的每个参数，如果在 vl 里有同名参数且形状一致，就直接覆盖
for name, param in qwen2coder_sd.items():
    if name in qwen2vl_backbone_sd and qwen2vl_backbone_sd[name].shape == param.shape:
        # 用 coder 的参数覆盖 VL 的对应参数
        with torch.no_grad():
            qwen2vl_backbone_sd[name].copy_(param)

# 将更新后的 state_dict load 回去
qwen2vl.model.load_state_dict(qwen2vl_backbone_sd)

qwen2vl_lm_head_sd = qwen2vl.lm_head.state_dict()
qwen2coder_lm_head_sd = qwen2coder.lm_head.state_dict()
for name, param in qwen2coder_lm_head_sd.items():
    if name in qwen2vl_lm_head_sd and qwen2vl_lm_head_sd[name].shape == param.shape:
        with torch.no_grad():
            qwen2vl_lm_head_sd[name].copy_(param)
qwen2vl.lm_head.load_state_dict(qwen2vl_lm_head_sd)

qwen2vl.save_pretrained("/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge")

/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 4/4 [00:47<00:00, 11.79s/it]

[2025-01-07 09:34:24,629] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)



/home/v-lingjiang/miniconda3/envs/llama/compiler_compat/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/home/v-lingjiang/miniconda3/envs/llama/compiler_compat/ld: warning: libpthread.so.0, needed by /usr/local/cuda/lib64/libcufile.so, not found (try using -rpath or -rpath-link)
/home/v-lingjiang/miniconda3/envs/llama/compiler_compat/ld: warning: libstdc++.so.6, needed by /usr/local/cuda/lib64/libcufile.so, not found (try using -rpath or -rpath-link)
/home/v-lingjiang/miniconda3/envs/llama/compiler_compat/ld: warning: libm.so.6, needed by /usr/local/cuda/lib64/libcufile.so, not found (try using -rpath or -rpath-link)
/home/v-lingjiang/miniconda3/envs/llama/compiler_compat/ld: /usr/local/cuda/lib64/libcufile.so: undefined reference to `std::runtime_error::~runtime_error()@GLIBCXX_3.4'
/home/v-lingjiang/miniconda3/envs/llama/compiler_compat/ld: /usr/local/cuda/lib64/libcufile.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
/home/v

In [2]:
qwen2coder.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0.0061,  0.0019,  0.0215],
        [ 0.0111, -0.0104,  0.0190,  ..., -0.0096, -0.0288, -0.0004],
        [-0.0347,  0.0058,  0.0007,  ..., -0.0161, -0.0286,  0.0098],
        ...,
        [ 0.0195,  0.0214,  0.0334,  ..., -0.0192,  0.0117, -0.0186],
        [ 0.0036,  0.0107, -0.0028,  ...,  0.0153,  0.0033, -0.0259],
        [-0.0261, -0.0107, -0.0253,  ..., -0.0219, -0.0067, -0.0229]],
       device='cuda:0', dtype=torch.bfloat16)

In [3]:
qwen2coder.lm_head.state_dict()["weight"]

tensor([[-0.0095, -0.0055,  0.0024,  ...,  0.0009, -0.0208,  0.0003],
        [-0.0045, -0.0003, -0.0183,  ...,  0.0079,  0.0031, -0.0026],
        [ 0.0064,  0.0092,  0.0058,  ...,  0.0008,  0.0047,  0.0051],
        ...,
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070],
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070],
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070]],
       device='cuda:0', dtype=torch.bfloat16)

In [4]:
qwen2vl.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0.0061,  0.0019,  0.0215],
        [ 0.0111, -0.0104,  0.0190,  ..., -0.0096, -0.0288, -0.0004],
        [-0.0347,  0.0058,  0.0007,  ..., -0.0161, -0.0286,  0.0098],
        ...,
        [ 0.0195,  0.0214,  0.0334,  ..., -0.0192,  0.0117, -0.0186],
        [ 0.0036,  0.0107, -0.0028,  ...,  0.0153,  0.0033, -0.0259],
        [-0.0261, -0.0107, -0.0253,  ..., -0.0219, -0.0067, -0.0229]],
       device='cuda:0', dtype=torch.bfloat16)

In [15]:
qwen2vl.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0.0061,  0.0019,  0.0215],
        [ 0.0111, -0.0104,  0.0190,  ..., -0.0096, -0.0288, -0.0004],
        [-0.0347,  0.0058,  0.0007,  ..., -0.0161, -0.0286,  0.0098],
        ...,
        [ 0.0195,  0.0214,  0.0334,  ..., -0.0192,  0.0117, -0.0186],
        [ 0.0036,  0.0107, -0.0028,  ...,  0.0153,  0.0033, -0.0259],
        [-0.0261, -0.0107, -0.0253,  ..., -0.0219, -0.0067, -0.0229]],
       device='cuda:0', dtype=torch.bfloat16)

In [5]:
qwen2vl.lm_head.state_dict()["weight"]

tensor([[-0.0095, -0.0055,  0.0024,  ...,  0.0009, -0.0208,  0.0003],
        [-0.0045, -0.0003, -0.0183,  ...,  0.0079,  0.0031, -0.0026],
        [ 0.0064,  0.0092,  0.0058,  ...,  0.0008,  0.0047,  0.0051],
        ...,
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070],
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070],
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070]],
       device='cuda:0', dtype=torch.bfloat16)

In [14]:
qwen2vl.lm_head.state_dict()["weight"]

tensor([[-0.0095, -0.0055,  0.0024,  ...,  0.0009, -0.0208,  0.0003],
        [-0.0045, -0.0003, -0.0183,  ...,  0.0079,  0.0031, -0.0026],
        [ 0.0064,  0.0092,  0.0058,  ...,  0.0008,  0.0047,  0.0051],
        ...,
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070],
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070],
        [ 0.0022,  0.0038, -0.0009,  ...,  0.0049,  0.0002, -0.0070]],
       device='cuda:0', dtype=torch.bfloat16)

In [16]:
qwen2vl.save_pretrained("/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge")

In [1]:
import torch
from transformers import (
    Qwen2VLForConditionalGeneration,  # Qwen2-VL
    AutoModelForCausalLM,                 # Qwen2 / Qwen2.5 coder
)
qwen2coder_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-Coder-7B-Instruct"
qwen2coder = AutoModelForCausalLM.from_pretrained(
    qwen2coder_model_path,
    torch_dtype="auto",
    device_map="auto"
)

qwen2vl_merged_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge"
qwen2vl_merged = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_merged_model_path,
    torch_dtype="auto",  
    device_map="auto"
)

/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 4/4 [00:31<00:00,  7.82s/it]
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 4/4 [00:33<00:00,  8.48s/it]


In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(qwen2vl_merged_model_path)

In [9]:
from transformers import AutoModelForCausalLM, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(qwen2vl_merged_model_path)
prompt = "write a quick sort algorithm."
messages = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(qwen2vl_merged.device)

generated_ids = qwen2vl_merged.generate(
    **model_inputs,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

In [11]:
print(response)

Certainly! Quick sort is a popular and efficient sorting algorithm that uses a divide-and-conquer approach to sort elements. Below is a Python implementation of the quick sort algorithm:

```python
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[len(arr) // 2]
        left = [x for x in arr if x < pivot]
        middle = [x for x in arr if x == pivot]
        right = [x for x in arr if x > pivot]
        return quick_sort(left) + middle + quick_sort(right)

# Example usage:
arr = [3, 6, 8, 10, 1, 2, 1]
sorted_arr = quick_sort(arr)
print(sorted_arr)
```

### Explanation:
1. **Base Case**: If the array has 0 or 1 elements, it is already sorted, so we return it as is.
2. **Pivot Selection**: We choose the pivot element. In this implementation, we select the middle element of the array.
3. **Partitioning**: We create three sub-arrays:
   - `left`: All elements less than the pivot.
   - `middle`: All elements equal to the pivot.
   - `right`: All 

In [ ]:
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

qwen2vl_merged_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge"
# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_merged_model_path, torch_dtype="auto", device_map="auto"
)

# default processer
processor = AutoProcessor.from_pretrained(qwen2vl_merged_model_path)

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)

`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46


Loading checkpoint shards: 100%|██████████| 4/4 [00:42<00:00, 10.57s/it]


['eczyneu1e12']


In [5]:
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)

['eczyneu1e12']


In [4]:
prompt = "write a quick sort algorithm."
messages = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)

['Certainly! Quick sort is a popular and efficient sorting algorithm that uses a divide-and-conquer approach to sort elements. Below is a Python implementation of the quick sort algorithm:\n\n```python\ndef quick_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    else:\n        pivot = arr[len(arr) // 2]\n        left = [x for x in arr if x < pivot]\n        middle = [x for x in arr if x == pivot]\n        right = [x for x in arr if x > pivot]\n        return quick_sort(left) + middle + quick_sort(right)\n\n# Example usage:\n']


In [5]:
qwen2coder.model.embed_tokens.state_dict()

OrderedDict([('weight',
              tensor([[-2.3438e-02,  1.3916e-02,  1.0010e-02,  ..., -1.0605e-03,
                       -1.3611e-02, -3.1982e-02],
                      [-6.7139e-03,  1.3123e-02,  8.1787e-03,  ..., -4.2114e-03,
                       -7.3624e-04,  4.4556e-03],
                      [-1.2390e-02,  3.8300e-03, -5.1270e-03,  ..., -1.3924e-04,
                       -2.4658e-02,  1.5076e-02],
                      ...,
                      [-1.1755e-37,  1.1755e-37,  1.1755e-37,  ..., -1.1755e-37,
                        1.1755e-37,  1.1755e-37],
                      [ 1.1755e-37, -1.1755e-37,  1.1755e-37,  ..., -1.1755e-37,
                        1.1755e-37, -1.1755e-37],
                      [ 1.1755e-37, -1.1755e-37, -1.1755e-37,  ...,  1.1755e-37,
                        1.1755e-37, -1.1755e-37]], device='cuda:0', dtype=torch.bfloat16))])

In [6]:
qwen2vl_merged.model.embed_tokens.state_dict()

OrderedDict([('weight',
              tensor([[-2.3438e-02,  1.3916e-02,  1.0010e-02,  ..., -1.0605e-03,
                       -1.3611e-02, -3.1982e-02],
                      [-6.7139e-03,  1.3123e-02,  8.1787e-03,  ..., -4.2114e-03,
                       -7.3624e-04,  4.4556e-03],
                      [-1.2390e-02,  3.8300e-03, -5.1270e-03,  ..., -1.3924e-04,
                       -2.4658e-02,  1.5076e-02],
                      ...,
                      [-1.1755e-37,  1.1755e-37,  1.1755e-37,  ..., -1.1755e-37,
                        1.1755e-37,  1.1755e-37],
                      [ 1.1755e-37, -1.1755e-37,  1.1755e-37,  ..., -1.1755e-37,
                        1.1755e-37, -1.1755e-37],
                      [ 1.1755e-37, -1.1755e-37, -1.1755e-37,  ...,  1.1755e-37,
                        1.1755e-37, -1.1755e-37]], device='cuda:0', dtype=torch.bfloat16))])

In [23]:
qwen2vl.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0028, -0.0022, -0.0062,  ..., -0.0008, -0.0070, -0.0095],
        [ 0.0015,  0.0016, -0.0266,  ..., -0.0061,  0.0048, -0.0142],
        [-0.0055,  0.0007,  0.0081,  ...,  0.0054,  0.0034,  0.0123],
        ...,
        [ 0.0063,  0.0091,  0.0216,  ...,  0.0025, -0.0002,  0.0031],
        [ 0.0080, -0.0080, -0.0238,  ..., -0.0273, -0.0067,  0.0123],
        [-0.0039, -0.0021,  0.0073,  ..., -0.0045,  0.0214,  0.0134]],
       device='cuda:0', dtype=torch.bfloat16)

In [8]:
qwen2_merge_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge"
qwen2vl = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_model_path,
    torch_dtype="auto",  
    device_map="auto"
)

Loading checkpoint shards: 100%|██████████| 5/5 [00:27<00:00,  5.45s/it]


In [9]:
qwen2vl.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0028, -0.0022, -0.0062,  ..., -0.0008, -0.0070, -0.0095],
        [ 0.0015,  0.0016, -0.0266,  ..., -0.0061,  0.0048, -0.0142],
        [-0.0055,  0.0007,  0.0081,  ...,  0.0054,  0.0034,  0.0123],
        ...,
        [ 0.0063,  0.0091,  0.0216,  ...,  0.0025, -0.0002,  0.0031],
        [ 0.0080, -0.0080, -0.0238,  ..., -0.0273, -0.0067,  0.0123],
        [-0.0039, -0.0021,  0.0073,  ..., -0.0045,  0.0214,  0.0134]],
       device='cuda:0', dtype=torch.bfloat16)

tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0.0061,  0.0019,  0.0215],
        [ 0.0111, -0.0104,  0.0190,  ..., -0.0096, -0.0288, -0.0004],
        [-0.0347,  0.0058,  0.0007,  ..., -0.0161, -0.0286,  0.0098],
        ...,
        [ 0.0195,  0.0214,  0.0334,  ..., -0.0192,  0.0117, -0.0186],
        [ 0.0036,  0.0107, -0.0028,  ...,  0.0153,  0.0033, -0.0259],
        [-0.0261, -0.0107, -0.0253,  ..., -0.0219, -0.0067, -0.0229]],
       device='cuda:0', dtype=torch.bfloat16)

In [2]:
print(model)

Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Seq

In [ ]:
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# qwen2vl_merged_model_path = "/mnt/lingjiejiang/multimodal_code/sft_checkpoints/qwen2_vl_coder_mn_only-7b_3072_bsz128_1e4_web2code_merger_2000"
qwen2vl_merged_model_path = "/mnt/lingjiejiang/multimodal_code/sft_checkpoints/qwen2_vl_coder_mn_pretrain_LLM_sft-7b_3072_bsz128_1e4_web2code_job_8000"
# default: Load the model on the available device(s)
sft_model = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_merged_model_path, torch_dtype="auto", device_map="auto"
)

from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

qwen2vl_merged_model_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge"
# default: Load the model on the available device(s)
model_merged = Qwen2VLForConditionalGeneration.from_pretrained(
    qwen2vl_merged_model_path, torch_dtype="auto", device_map="auto"
)
import torch  
sft_model_params = sft_model.state_dict()  
model_merged_params = model_merged.state_dict()  
def compare_models_params(model1_params, model2_params):  
    different_params = []  
    for key in model1_params.keys():  
        if key not in model2_params:  
            different_params.append((key, "Missing in model2"))  
        elif not torch.equal(model1_params[key], model2_params[key]):  
            different_params.append((key, "Different weights"))  
      
    for key in model2_params.keys():  
        if key not in model1_params:  
            different_params.append((key, "Missing in model1"))  

    return different_params  

differences = compare_models_params(sft_model_params, model_merged_params)  

print(differences)

/home/v-lingjiang/miniconda3/envs/llama/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 4/4 [02:58<00:00, 44.53s/it]


[('visual.merger.ln_q.weight', 'Different weights'), ('visual.merger.ln_q.bias', 'Different weights'), ('visual.merger.mlp.0.weight', 'Different weights'), ('visual.merger.mlp.0.bias', 'Different weights'), ('visual.merger.mlp.2.weight', 'Different weights'), ('visual.merger.mlp.2.bias', 'Different weights'), ('model.layers.0.self_attn.q_proj.weight', 'Different weights'), ('model.layers.0.self_attn.k_proj.weight', 'Different weights'), ('model.layers.0.self_attn.v_proj.weight', 'Different weights'), ('model.layers.0.self_attn.o_proj.weight', 'Different weights'), ('model.layers.0.mlp.gate_proj.weight', 'Different weights'), ('model.layers.0.mlp.up_proj.weight', 'Different weights'), ('model.layers.0.mlp.down_proj.weight', 'Different weights'), ('model.layers.1.self_attn.q_proj.weight', 'Different weights'), ('model.layers.1.self_attn.k_proj.weight', 'Different weights'), ('model.layers.1.self_attn.v_proj.weight', 'Different weights'), ('model.layers.1.self_attn.o_proj.weight', 'Differ

In [2]:
differences

[('visual.merger.ln_q.weight', 'Different weights'),
 ('visual.merger.ln_q.bias', 'Different weights'),
 ('visual.merger.mlp.0.weight', 'Different weights'),
 ('visual.merger.mlp.0.bias', 'Different weights'),
 ('visual.merger.mlp.2.weight', 'Different weights'),
 ('visual.merger.mlp.2.bias', 'Different weights'),
 ('model.layers.0.self_attn.q_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.k_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.v_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.o_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.gate_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.up_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.down_proj.weight', 'Different weights'),
 ('model.layers.1.self_attn.q_proj.weight', 'Different weights'),
 ('model.layers.1.self_attn.k_proj.weight', 'Different weights'),
 ('model.layers.1.self_attn.v_proj.weight', 'Different weights'),
 ('model.layers.1.self_attn.o_proj.

In [6]:
sft_model

Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Seq

In [5]:
model_merged.visual.merger.state_dict()

OrderedDict([('ln_q.weight',
              tensor([1.2969, 1.2891, 1.2734,  ..., 1.2031, 1.2656, 1.2422], device='cuda:0',
                     dtype=torch.bfloat16)),
             ('ln_q.bias',
              tensor([-0.0320, -0.0211, -0.0232,  ..., -0.0361, -0.0139, -0.0265],
                     device='cuda:0', dtype=torch.bfloat16)),
             ('mlp.0.weight',
              tensor([[ 0.0547, -0.0205, -0.0082,  ..., -0.0498, -0.0376,  0.0464],
                      [-0.0205, -0.0155,  0.0447,  ...,  0.0150,  0.0151, -0.0132],
                      [ 0.0127, -0.0520,  0.0422,  ..., -0.0437,  0.0123, -0.0222],
                      ...,
                      [ 0.0079, -0.0410, -0.0266,  ..., -0.0488, -0.0096,  0.0327],
                      [-0.0161, -0.0165, -0.0221,  ..., -0.0151, -0.0227, -0.0344],
                      [-0.0026,  0.0091, -0.0234,  ..., -0.0135, -0.0210, -0.0041]],
                     device='cuda:0', dtype=torch.bfloat16)),
             ('mlp.0.bias',
        

In [2]:
differences

[('model.embed_tokens.weight', 'Different weights'),
 ('model.layers.0.self_attn.q_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.q_proj.bias', 'Different weights'),
 ('model.layers.0.self_attn.k_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.k_proj.bias', 'Different weights'),
 ('model.layers.0.self_attn.v_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.v_proj.bias', 'Different weights'),
 ('model.layers.0.self_attn.o_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.gate_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.up_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.down_proj.weight', 'Different weights'),
 ('model.layers.0.input_layernorm.weight', 'Different weights'),
 ('model.layers.0.post_attention_layernorm.weight', 'Different weights'),
 ('model.layers.1.self_attn.q_proj.weight', 'Different weights'),
 ('model.layers.1.self_attn.q_proj.bias', 'Different weights'),
 ('model.layers.1.self_attn.k_proj.

In [9]:
sft_model = sft_model.to('cpu')  
model_merged = model_merged.to('cpu')  

You shouldn't move a model that is dispatched using accelerate hooks.


RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

In [8]:
import torch  
sft_model_params = sft_model.state_dict()  
model_merged_params = model_merged.state_dict()  
def compare_models_params(model1_params, model2_params):  
    different_params = []  
    for key in model1_params.keys():  
        if key not in model2_params:  
            different_params.append((key, "Missing in model2"))  
        elif not torch.equal(model1_params[key], model2_params[key]):  
            different_params.append((key, "Different weights"))  
      
    for key in model2_params.keys():  
        if key not in model1_params:  
            different_params.append((key, "Missing in model1"))  

    return different_params  

differences = compare_models_params(sft_model_params, model_merged_params)  

NotImplementedError: aten::equal: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl. Please see the following for next steps:  https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html

In [4]:
print(model_merged)

Qwen2VLForConditionalGeneration(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): Linear(in_features=1280, out_features=3840, bias=True)
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Seq

In [4]:
differences

[('visual.patch_embed.proj.weight', 'Different weights'),
 ('visual.blocks.0.norm1.weight', 'Different weights'),
 ('visual.blocks.0.norm1.bias', 'Different weights'),
 ('visual.blocks.0.norm2.weight', 'Different weights'),
 ('visual.blocks.0.norm2.bias', 'Different weights'),
 ('visual.blocks.0.attn.qkv.weight', 'Different weights'),
 ('visual.blocks.0.attn.qkv.bias', 'Different weights'),
 ('visual.blocks.0.attn.proj.weight', 'Different weights'),
 ('visual.blocks.0.attn.proj.bias', 'Different weights'),
 ('visual.blocks.0.mlp.fc1.weight', 'Different weights'),
 ('visual.blocks.0.mlp.fc1.bias', 'Different weights'),
 ('visual.blocks.0.mlp.fc2.weight', 'Different weights'),
 ('visual.blocks.0.mlp.fc2.bias', 'Different weights'),
 ('visual.blocks.1.norm1.weight', 'Different weights'),
 ('visual.blocks.1.norm1.bias', 'Different weights'),
 ('visual.blocks.1.norm2.weight', 'Different weights'),
 ('visual.blocks.1.norm2.bias', 'Different weights'),
 ('visual.blocks.1.attn.qkv.weight', 'Di

In [3]:
differences

[('model.embed_tokens.weight', 'Different weights'),
 ('model.layers.0.self_attn.q_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.q_proj.bias', 'Different weights'),
 ('model.layers.0.self_attn.k_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.k_proj.bias', 'Different weights'),
 ('model.layers.0.self_attn.v_proj.weight', 'Different weights'),
 ('model.layers.0.self_attn.v_proj.bias', 'Different weights'),
 ('model.layers.0.self_attn.o_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.gate_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.up_proj.weight', 'Different weights'),
 ('model.layers.0.mlp.down_proj.weight', 'Different weights'),
 ('model.layers.0.input_layernorm.weight', 'Different weights'),
 ('model.layers.0.post_attention_layernorm.weight', 'Different weights'),
 ('model.layers.1.self_attn.q_proj.weight', 'Different weights'),
 ('model.layers.1.self_attn.q_proj.bias', 'Different weights'),
 ('model.layers.1.self_attn.k_proj.

In [11]:
sft_model.visual.merger.state_dict()

OrderedDict([('ln_q.weight',
              tensor([1.2969, 1.2891, 1.2734,  ..., 1.2031, 1.2656, 1.2422], device='cuda:0',
                     dtype=torch.bfloat16)),
             ('ln_q.bias',
              tensor([-0.0320, -0.0211, -0.0232,  ..., -0.0361, -0.0139, -0.0265],
                     device='cuda:0', dtype=torch.bfloat16)),
             ('mlp.0.weight',
              tensor([[ 0.0547, -0.0205, -0.0082,  ..., -0.0498, -0.0376,  0.0464],
                      [-0.0205, -0.0155,  0.0447,  ...,  0.0150,  0.0151, -0.0132],
                      [ 0.0127, -0.0520,  0.0422,  ..., -0.0437,  0.0123, -0.0222],
                      ...,
                      [ 0.0079, -0.0410, -0.0266,  ..., -0.0488, -0.0096,  0.0327],
                      [-0.0161, -0.0165, -0.0221,  ..., -0.0151, -0.0227, -0.0344],
                      [-0.0026,  0.0091, -0.0234,  ..., -0.0135, -0.0210, -0.0041]],
                     device='cuda:0', dtype=torch.bfloat16)),
             ('mlp.0.bias',
        

In [12]:
model_merged.visual.merger.state_dict()

OrderedDict([('ln_q.weight',
              tensor([1.2969, 1.2891, 1.2734,  ..., 1.2031, 1.2656, 1.2422], device='cuda:0',
                     dtype=torch.bfloat16)),
             ('ln_q.bias',
              tensor([-0.0320, -0.0211, -0.0232,  ..., -0.0361, -0.0139, -0.0265],
                     device='cuda:0', dtype=torch.bfloat16)),
             ('mlp.0.weight',
              tensor([[ 0.0547, -0.0205, -0.0082,  ..., -0.0498, -0.0376,  0.0464],
                      [-0.0205, -0.0155,  0.0447,  ...,  0.0150,  0.0151, -0.0132],
                      [ 0.0127, -0.0520,  0.0422,  ..., -0.0437,  0.0123, -0.0222],
                      ...,
                      [ 0.0079, -0.0410, -0.0266,  ..., -0.0488, -0.0096,  0.0327],
                      [-0.0161, -0.0165, -0.0221,  ..., -0.0151, -0.0227, -0.0344],
                      [-0.0026,  0.0091, -0.0234,  ..., -0.0135, -0.0210, -0.0041]],
                     device='cuda:0', dtype=torch.bfloat16)),
             ('mlp.0.bias',
        

In [2]:
model_merged.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0.0061,  0.0019,  0.0215],
        [ 0.0111, -0.0104,  0.0190,  ..., -0.0096, -0.0288, -0.0004],
        [-0.0347,  0.0058,  0.0007,  ..., -0.0161, -0.0286,  0.0098],
        ...,
        [ 0.0195,  0.0214,  0.0334,  ..., -0.0192,  0.0117, -0.0186],
        [ 0.0036,  0.0107, -0.0028,  ...,  0.0153,  0.0033, -0.0259],
        [-0.0261, -0.0107, -0.0253,  ..., -0.0219, -0.0067, -0.0229]],
       device='cuda:0', dtype=torch.bfloat16)

In [3]:
model_merged.model.state_dict()["layers.0.self_attn.q_proj.weight"]

tensor([[ 0.0176, -0.0139,  0.0269,  ..., -0.0061,  0.0019,  0.0215],
        [ 0.0111, -0.0104,  0.0190,  ..., -0.0096, -0.0288, -0.0004],
        [-0.0347,  0.0058,  0.0007,  ..., -0.0161, -0.0286,  0.0098],
        ...,
        [ 0.0195,  0.0214,  0.0334,  ..., -0.0192,  0.0117, -0.0186],
        [ 0.0036,  0.0107, -0.0028,  ...,  0.0153,  0.0033, -0.0259],
        [-0.0261, -0.0107, -0.0253,  ..., -0.0219, -0.0067, -0.0229]],
       device='cuda:0', dtype=torch.bfloat16)

In [26]:
from transformers import AutoTokenizer, Qwen2VLForConditionalGeneration, Qwen2ForCausalLM  
  
# 加载 Qwen2Coder 的 tokenizer  
qwen2coder_tokenizer_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-7B-Instruct"  
qwen2coder_tokenizer = AutoTokenizer.from_pretrained(qwen2coder_tokenizer_path)  
   
qwen2vl_tokenizer_path = "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct"  
qwen2vl_tokenizer = AutoTokenizer.from_pretrained(qwen2vl_tokenizer_path)
# qwen2coder_tokenizer.save_pretrained(qwen2vl_tokenizer_path)  
  
# # 在保存的新目录中，确保模型和 tokenizer 都被正确保存  
# qwen2vl.save_pretrained(qwen2vl_tokenizer_path)  

In [45]:
qwen2coder_tokenizer

Qwen2TokenizerFast(name_or_path='/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-7B-Instruct', vocab_size=151643, model_max_length=131072, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151646: AddedToken("<|object_ref_start|>", 

In [30]:
qwen2vl_tokenizer

Qwen2TokenizerFast(name_or_path='/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct', vocab_size=151643, model_max_length=32768, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151646: AddedToken("<|obj

In [38]:
from transformers import AutoTokenizer  
  
# 加载 Qwen2Coder 的 tokenizer  
qwen2coder_tokenizer_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-Coder-7B-Instruct"  
qwen2coder_tokenizer = AutoTokenizer.from_pretrained(qwen2coder_tokenizer_path)  
  
# 加载 Qwen2VL 的 tokenizer  
qwen2vl_tokenizer_path = "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct"  
qwen2vl_tokenizer = AutoTokenizer.from_pretrained(qwen2vl_tokenizer_path)  
  
# 获取两个词表的词汇和 ID  
qwen2coder_vocab = qwen2coder_tokenizer.get_vocab()  
qwen2vl_vocab = qwen2vl_tokenizer.get_vocab()  
  
# 反转字典以便通过 ID 获取 token  
qwen2coder_id_to_token = {v: k for k, v in qwen2coder_vocab.items()}  
  
# 找到需要替换和添加的 token  
tokens_to_replace = {}  
tokens_to_add = {}  
  
# 查找需要替换的 token  
for token, vl_id in qwen2vl_vocab.items():  
    if token in qwen2coder_vocab:  
        coder_id = qwen2coder_vocab[token]  
        if vl_id != coder_id:  
            tokens_to_replace[vl_id] = qwen2coder_id_to_token[coder_id]  
    else:  
        tokens_to_add[token] = vl_id  
  
# 添加 qwen2coder 中有但 qwen2vl 中没有的 token，直接使用 coder 的 ID  
for token, coder_id in qwen2coder_vocab.items():  
    if token not in qwen2vl_vocab:  
        tokens_to_add[token] = coder_id  
  
# # 更新 qwen2vl 的词表  
updated_vocab = qwen2vl_vocab.copy()  
for vl_id, coder_token in tokens_to_replace.items():  
    updated_vocab[coder_token] = vl_id  
  
for token, coder_id in tokens_to_add.items():  
    updated_vocab[token] = coder_id  
  
# # 创建新的 tokenizer  
# updated_tokenizer = qwen2vl_tokenizer  
# updated_tokenizer.vocab = updated_vocab  
# updated_tokenizer.ids_to_tokens = {v: k for k, v in updated_vocab.items()}  
  
# # 保存更新后的 tokenizer  
# updated_tokenizer.save_pretrained("/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_updated")  

AttributeError: can't set attribute 'vocab'

In [42]:
max(qwen2vl_vocab.values())

151656

In [7]:
import os, shutil
from transformers import AutoTokenizer

# 你已经在代码中加载了 Qwen2-VL
qwen2vl_model_path = "/mnt/lingjiejiang/textual_aesthetics/model_checkpoint/vlm_checkpoints/Qwen2-VL-7B-Instruct"
# qwen2vl = Qwen2VLForConditionalGeneration.from_pretrained(...)
# /mnt/lingjiejiang/multimodal_code/checkpoints/llms/Qwen2.5-Coder-7B-Instruct
# 你的新模型保存目录
merged_path = "/mnt/lingjiejiang/multimodal_code/checkpoints/vlms/Qwenvl2-coder2.5-7B-Instruct_merge"

# 如果你也加载了原 Qwen2-VL 的 tokenizer:
vl_tokenizer = AutoTokenizer.from_pretrained(qwen2vl_model_path)
# 直接保存到新目录
vl_tokenizer.save_pretrained(merged_path)

# 某些 Qwen2-VL 版本还带有 "processor" 或 "chat_template.json"，也可类似保存或复制
# 如果原目录下有 chat_template.json，可以直接 shutil.copy
src_chat_template = os.path.join(qwen2vl_model_path, "chat_template.json")
dst_chat_template = os.path.join(merged_path, "chat_template.json")
if os.path.exists(src_chat_template):
    shutil.copy(src_chat_template, dst_chat_template)

# 如果有 preprocessor_config.json，也可以类似处理
src_preproc_config = os.path.join(qwen2vl_model_path, "preprocessor_config.json")
dst_preproc_config = os.path.join(merged_path, "preprocessor_config.json")
if os.path.exists(src_preproc_config):
    shutil.copy(src_preproc_config, dst_preproc_config)

print("All done. Check the merged_path folder to see if tokenizer & chat_template are there.")


All done. Check the merged_path folder to see if tokenizer & chat_template are there.


In [44]:
sorted(tokens_to_add.values())

[151657, 151658, 151659, 151660, 151661, 151662, 151663, 151664]